# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3910740fe073643ab72f12ac24b4872ebb862d80c04e32aa48670267675710636a61f1f62500d5a2e37f765bc67a3671942cea996b02b0dad21d94609b8d36fe

test:
  secret_key_base: 6d02afee99b596ef3d86396e779eb94a503db9280b6fded1fff205c0905a77cdbcf9d47362e267a508e16748ba8e08703efa1860a99eeb6b50e978b5e09af82e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
